apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-namespace
  name: kyverno-namespace-role
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: my-namespace
  name: kyverno-namespace-rolebinding
subjects:
- kind: User
  name: my-user
roleRef:
  kind: Role
  name: kyverno-namespace-role
  apiGroup: rbac.authorization.k8s.io
