apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cleanup-tekton-pipelinerun
  annotations:
    policies.kyverno.io/title: Cleanup for Tekton PipelineRun
    policies.kyverno.io/category: Tekton
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PipelineRun
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >- 
      Policy Cleanup after 5 hours	.    
spec:
  rules:
  - name: expire-five-hours
    match:
      any:
      - resources:
          kinds:
          - PipelineRun
    generate:
      apiVersion: kyverno.io/v2beta1
      kind: ClusterCleanupPolicy
      name: pipex-{{ request.namespace }}-{{ request.object.metadata.name }}-{{ random('[0-9a-z]{8}') }}
      synchronize: false
      data:
        metadata:
          labels:
            kyverno.io/automated: "true"
        spec:
          schedule: "{{ time_add('{{ time_now_utc() }}','5h') | time_to_cron(@) }}"
          match:
            any:
            - resources:
                kinds:
                  - PipelineRun
                namespaces:
                - "{{ request.namespace }}"
                names:
                - "{{ request.object.metadata.name }}"
