apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-service-account
  namespace: ${NAMESPACE_NAME}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        iam.gke.io/gcp-service-account: redis-service-account@${PROJECT_ID}.iam.gserviceaccount.com
    spec:
      serviceAccountName: redis-service-account
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
