name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up AKS credentials
        run: |
          az aks get-credentials --resource-group <your-aks-resource-group> --name <your-aks-cluster-name>

      - name: Deploy to AKS
        run: |
          # Use Azure CLI to deploy ACR image to AKS
          az aks update -n <your-aks-cluster-name> -g <your-aks-resource-group> --attach-acr <your-acr-name>

          # Deploy to AKS using kubectl
          kubectl apply -f <your-k8s-manifest-file>.yaml